"""initial schema

Revision ID: 45cf6b896517
Revises: 
Create Date: 2026-08-14 01:41:09.905383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45cf6b896517'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_api_key'), 'clients', ['api_key'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processed', 'failed', name='processing_status'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_name'), 'events', ['event_name'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('sample_percent', sa.Integer(), nullable=False),
    sa.Column('dedup_window_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rules_client_event_active', 'rules', ['client_id', 'event_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_rules_event_name'), 'rules', ['event_name'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'skipped_sampled_out', 'skipped_duplicate', 'failed', name='dispatch_status'), nullable=False),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_due_at'), 'dispatches', ['due_at'], unique=False)
    op.create_index(op.f('ix_dispatches_status'), 'dispatches', ['status'], unique=False)
    op.create_index('ix_dispatches_status_due_at', 'dispatches', ['status', 'due_at'], unique=False)
    op.create_index(op.f('ix_dispatches_user_id'), 'dispatches', ['user_id'], unique=False)
    op.create_index('ix_dispatches_user_interview_created', 'dispatches', ['user_id', 'interview_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dispatches_user_interview_created', table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_user_id'), table_name='dispatches')
    op.drop_index('ix_dispatches_status_due_at', table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_status'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_due_at'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_rules_event_name'), table_name='rules')
    op.drop_index('ix_rules_client_event_active', table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_name'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_clients_api_key'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
