"""scope dedup index by client

Revision ID: ddbb7d3f8102
Revises: 45cf6b896517
Create Date: 2026-08-14 12:42:08.741498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbb7d3f8102'
down_revision: Union[str, None] = '45cf6b896517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dispatches_user_interview_created', table_name='dispatches')
    op.create_index('ix_dispatches_client_user_interview_created', 'dispatches', ['client_id', 'user_id', 'interview_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dispatches_client_user_interview_created', table_name='dispatches')
    op.create_index('ix_dispatches_user_interview_created', 'dispatches', ['user_id', 'interview_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
